# NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even tools like Pandas are built around the NumPy array.
Numpy arrays can be thought of as **mathematical vectors** and behave correspondingly; contrary to Python lists, which are a container that stores arbitrary objects.



## NumPy Array Attributes

First let's discuss some useful array attributes.
We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.
We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run.

The old way is to set a global state, but this is "bad practice" and can lead to subtle bugs.
The new way is to use a ``numpy.random.RandomState`` object, which can generate random numbers in a way that is isolated from the global state.

(Correct random number generation is **hard**!)

In [2]:
import numpy as np

np.random.seed(0)  # global seed for reproducibility
rndgen = np.random.RandomState(42)

x1 = rndgen.normal(0, 10, size=6)  # One-dimensional array
x2 = rndgen.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.normal(2, 3, size=(3, 4, 5))  # Three-dimensional array  # we can use numpy, but this relies on the global seed

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [3]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Another useful attribute is the ``dtype``, the data type of the array

In [4]:
print("dtype:", x3.dtype)

dtype: float64


## Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [5]:
x1

array([ 4.96714153, -1.38264301,  6.47688538, 15.23029856, -2.34153375,
       -2.34136957])

In [6]:
x1[0]

np.float64(4.967141530112327)

In [7]:
x1[4]

np.float64(-2.3415337472333597)

To index from the end of the array, you can use negative indices:

In [8]:
x1[-1]

np.float64(-2.3413695694918055)

In [9]:
x1[-2]

np.float64(-2.3415337472333597)

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [10]:
x2

array([[7, 4, 3, 7],
       [7, 2, 5, 4],
       [1, 7, 5, 1]])

In [11]:
x2[0, 0]

np.int64(7)

In [12]:
x2[2, 0]

np.int64(1)

In [13]:
x2[2, -1]

np.int64(1)

Values can also be modified using any of the above index notation:

In [14]:
x2[0, 0] = 12
x2

array([[12,  4,  3,  7],
       [ 7,  2,  5,  4],
       [ 1,  7,  5,  1]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [16]:
x2[0, 0] = 3.14159  # this will be truncated!
x2

array([[3, 4, 3, 7],
       [7, 2, 5, 4],
       [1, 7, 5, 1]])

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [21]:
x = np.linspace(0, 10, 10)
x

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [22]:
x[:5]  # first five elements

array([0.        , 1.11111111, 2.22222222, 3.33333333, 4.44444444])

In [23]:
x[5:]  # elements after index 5

array([ 5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [24]:
x[4:7]  # middle sub-array

array([4.44444444, 5.55555556, 6.66666667])

In [25]:
x[::2]  # every other element

array([0.        , 2.22222222, 4.44444444, 6.66666667, 8.88888889])

In [26]:
x[1::2]  # every other element, starting at index 1

array([ 1.11111111,  3.33333333,  5.55555556,  7.77777778, 10.        ])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [27]:
x[::-1]  # all elements, reversed

array([10.        ,  8.88888889,  7.77777778,  6.66666667,  5.55555556,
        4.44444444,  3.33333333,  2.22222222,  1.11111111,  0.        ])

In [28]:
x[5::-2]  # reversed every other from index 5

array([5.55555556, 3.33333333, 1.11111111])

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [29]:
x2

array([[3, 4, 3, 7],
       [7, 2, 5, 4],
       [1, 7, 5, 1]])

In [30]:
x2[:2, :3]  # two rows, three columns

array([[3, 4, 3],
       [7, 2, 5]])

In [31]:
x2[:3, ::2]  # all rows, every other column

array([[3, 3],
       [7, 5],
       [1, 5]])

Finally, subarray dimensions can even be reversed together:

In [32]:
x2[::-1, ::-1]

array([[1, 5, 7, 1],
       [4, 5, 2, 7],
       [7, 3, 4, 3]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [33]:
print(x2[:, 0])  # first column of x2

[3 7 1]


In [34]:
print(x2[0, :])  # first row of x2

[3 4 3 7]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [35]:
print(x2[0])  # equivalent to x2[0, :]

[3 4 3 7]


### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [36]:
print(x2)

[[3 4 3 7]
 [7 2 5 4]
 [1 7 5 1]]


Let's extract a $2 \times 2$ subarray from this:

In [37]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 4]
 [7 2]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [38]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  4]
 [ 7  2]]


In [39]:
print(x2)

[[99  4  3  7]
 [ 7  2  5  4]
 [ 1  7  5  1]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [40]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  4]
 [ 7  2]]


If we now modify this subarray, the original array is not touched:

In [41]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  4]
 [ 7  2]]


In [42]:
print(x2)

[[99  4  3  7]
 [ 7  2  5  4]
 [ 1  7  5  1]]


## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [43]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [44]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


## Operations on NumPy Arrays

NumPy provides a number of functions to perform operations on NumPy arrays that are much more efficient than looping over the arrays.
They fall into three categories:
- *unary* operations, which operate on a single array
- *binary* operations, which operate on two arrays
- *aggregates*, which summarize the values in an array

In general, they act like mathematical vectors.

In [52]:
shape = (3, 4)
x = rndgen.normal(0, 10, size=shape)
y = rndgen.normal(5, 1, size=shape)

In [53]:
x * 3  # multiply each element by 3

array([[-57.39840734, -51.74753498, -16.86862588, -30.38493361],
       [  9.42741998, -27.24072227, -42.36911104,  43.96946307],
       [ -6.77328901,   2.02584614, -42.74244559, -16.33148174]])

In [54]:
x + y  # add each element of x to the corresponding element of y

array([[-14.02187986, -13.4001719 ,  -0.24717727,  -5.72894989],
       [  7.85077958,  -4.68194737,  -7.27075883,  19.64299046],
       [  1.68452607,   6.49782696, -10.46832551,  -0.23496365]])

In [55]:
np.maximum(x, y)  # element-wise maximum

array([[ 5.11092259,  3.84900642,  5.37569802,  4.39936131],
       [ 4.70830625,  4.39829339,  6.85227818, 14.65648769],
       [ 3.94228907,  5.82254491,  3.77915635,  5.2088636 ]])

In [56]:
np.cos(x)  # cosine of each element

array([[ 0.96015318, -0.02957696,  0.78980212, -0.76256124],
       [-0.99999961, -0.94123187,  0.01412946, -0.49629056],
       [-0.63419482,  0.78053067, -0.11009131,  0.6679407 ]])

### Aggregation

Aggregates are functions that summarize the values in an array, they can be only over some axis or over the whole array.

In [57]:
np.sum(x)  # sum of all elements

np.float64(-78.81127408623152)

In [58]:
np.sum(x, axis=0)  # sum of each column

array([-18.24809213, -25.65413703, -33.99339417,  -0.91565076])

### Boolean operations

NumPy also implements comparison operators such as ``<`` (less than) and ``>`` (greater than) or ``==`` (equal) as element-wise functions.
What do you expect the following to return?

In [59]:
x < 5

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True]])

In [60]:
x == y

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### Boolean indexing

Boolean indexing is a powerful feature that allows you to select elements of an array that satisfy some condition.
Using a boolean mask, you can index an array where the elements are selected where the mask is ``True``.

In [63]:
select_lt1 = x < 1
select_lt1

array([[ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True,  True]])

In [65]:
x[select_lt1]

array([-19.13280245, -17.24917833,  -5.62287529, -10.1283112 ,
        -9.08024076, -14.12303701,  -2.257763  ,   0.67528205,
       -14.24748186,  -5.44382725])

This operation is particularly useful for filtering data.

A problem of our data  is that we have to remember which row corresponds to which column, as they are only numbers.